### ISSUE TITLE
Getting Data for specific pokemon

### ISSUE THREAD

**Issue by Fyreek** [tmwilder/pogoiv#10]
So i noticed that i can't get data for either the female Nidoran or the mal Nidoran.
I tried: Nidoran_female, Nidoran♀, Nidoran_f and so on.
Is there a way that this works?

Same thing does not work for Mr_mime.

**Comment by Fyreek** [comment]
Okay I found out that "Mr_mime" is actually "Mr. Mime".
But I still don't know about Nidoran.

**Comment by tmwilder** [comment]
Hi @Fyreek - thanks for the bug report! I can confirm that this is definitely a real bug and will fix. The data source I pulled in is using Nidoran♀ with the ♀ character - there may be a serialization / utf8 conversion problem here, I'll look into it when I get a chance.

**Comment by tmwilder** [comment]
Hi @Fyreek - I've pushed an update to support non ascii Pokemon names like Nidoran♀, let me know if this is not working for you after the change!
