### ISSUE TITLE
Too much results.

### ISSUE THREAD

**Issue by Fyreek** [tmwilder/pogoiv#13]
I noticed that often you get at least 5 results, also the estimated Stats are varying widely.

I found this Site: https://thesilphroad.com/research which is getting the exact Pokemon Stats every time so far.
Maybe you could take a look at this?

**Comment by tmwilder** [comment]
The missing component is the IV arc slider which removes significant variability by narrowing the pokemon's level to a known as long as the user inputs the slide correctly. We could add a backend piece that analyzes that, although it wouldn't work particularly well from a CLI. For that to be meaningful I or a consumer of the project needs to find some time to implement a web app that will aid the user in inputting a correct arc position.
