### ISSUE TITLE
Better guessing pokemon level using trainer level

### ISSUE THREAD

**Issue by gorilasso** [tmwilder/pogoiv#7]
At the moment the range use is as described in this line https://github.com/tmwilder/pogoiv/blob/1f1bc4413252ec4f62185c482e8f01612bc1cbd2/pogoiv/level_dust_costs.py#L33

But since the maximum level is equal to the trainer level + 1.5, would it be better to use this instead?

**Comment by tmwilder** [comment]
Interesting idea Gorilasso! We could certainly add that since the added constraint would remove some possible scenarios in cases where a Pokemon is close to the cap.

**Comment by tmwilder** [comment]
I thought about this more and realized that dust cost is already constraining that value - thank you for the idea though.
