### ISSUE TITLE
Checking without powerup gives a bit much data.

### ISSUE THREAD

**Issue by ollemonster** [tmwilder/pogoiv#8]
Lots of data sounds good usually but when you just want to check 50 pokémons to see which one you should evolve you need the short version. I ran this:

from pogoiv.iv_calculator import IvCalculator
calculator = IvCalculator()
result = calculator.get_ivs('Caterpie', 14, 16, 200, powered=False)
print result
And got this:

[{'atk_iv': 0, 'def_iv': 0, 'stam_iv': 11, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 0, 'stam_iv': 12, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 1, 'stam_iv': 10, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 1, 'stam_iv': 11, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 1, 'stam_iv': 12, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 2, 'stam_iv': 8, 'perfection': 22.2, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 2, 'stam_iv': 9, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 2, 'stam_iv': 10, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 2, 'stam_iv': 11, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 2, 'stam_iv': 12, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 3, 'stam_iv': 7, 'perfection': 22.2, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 3, 'stam_iv': 8, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 3, 'stam_iv': 9, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 3, 'stam_iv': 10, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 3, 'stam_iv': 11, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 3, 'stam_iv': 12, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 4, 'stam_iv': 7, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 4, 'stam_iv': 8, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 4, 'stam_iv': 9, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 4, 'stam_iv': 10, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 4, 'stam_iv': 11, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 4, 'stam_iv': 12, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 5, 'stam_iv': 7, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 5, 'stam_iv': 8, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 5, 'stam_iv': 9, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 5, 'stam_iv': 10, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 5, 'stam_iv': 11, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 5, 'stam_iv': 12, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 6, 'stam_iv': 7, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 6, 'stam_iv': 8, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 6, 'stam_iv': 9, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 6, 'stam_iv': 10, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 6, 'stam_iv': 11, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 6, 'stam_iv': 12, 'perfection': 40.0, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 7, 'stam_iv': 7, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 7, 'stam_iv': 8, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 7, 'stam_iv': 9, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 7, 'stam_iv': 10, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 7, 'stam_iv': 11, 'perfection': 40.0, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 7, 'stam_iv': 12, 'perfection': 42.2, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 8, 'stam_iv': 7, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 8, 'stam_iv': 8, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 8, 'stam_iv': 9, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 8, 'stam_iv': 10, 'perfection': 40.0, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 8, 'stam_iv': 11, 'perfection': 42.2, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 8, 'stam_iv': 12, 'perfection': 44.4, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 9, 'stam_iv': 7, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 9, 'stam_iv': 8, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 9, 'stam_iv': 9, 'perfection': 40.0, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 9, 'stam_iv': 10, 'perfection': 42.2, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 9, 'stam_iv': 11, 'perfection': 44.4, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 10, 'stam_iv': 7, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 10, 'stam_iv': 8, 'perfection': 40.0, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 10, 'stam_iv': 9, 'perfection': 42.2, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 10, 'stam_iv': 10, 'perfection': 44.4, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 11, 'stam_iv': 7, 'perfection': 40.0, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 11, 'stam_iv': 8, 'perfection': 42.2, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 11, 'stam_iv': 9, 'perfection': 44.4, 'level': 2.0}, {'atk_iv': 0, 'def_iv': 12, 'stam_iv': 7, 'perfection': 42.2, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 0, 'stam_iv': 8, 'perfection': 20.0, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 0, 'stam_iv': 9, 'perfection': 22.2, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 0, 'stam_iv': 10, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 0, 'stam_iv': 11, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 0, 'stam_iv': 12, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 1, 'stam_iv': 7, 'perfection': 20.0, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 1, 'stam_iv': 8, 'perfection': 22.2, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 1, 'stam_iv': 9, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 1, 'stam_iv': 10, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 1, 'stam_iv': 11, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 1, 'stam_iv': 12, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 2, 'stam_iv': 7, 'perfection': 22.2, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 2, 'stam_iv': 8, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 2, 'stam_iv': 9, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 2, 'stam_iv': 10, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 2, 'stam_iv': 11, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 2, 'stam_iv': 12, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 3, 'stam_iv': 7, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 3, 'stam_iv': 8, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 3, 'stam_iv': 9, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 3, 'stam_iv': 10, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 3, 'stam_iv': 11, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 3, 'stam_iv': 12, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 4, 'stam_iv': 7, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 4, 'stam_iv': 8, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 4, 'stam_iv': 9, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 4, 'stam_iv': 10, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 4, 'stam_iv': 11, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 4, 'stam_iv': 12, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 5, 'stam_iv': 7, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 5, 'stam_iv': 8, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 5, 'stam_iv': 9, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 5, 'stam_iv': 10, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 5, 'stam_iv': 11, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 5, 'stam_iv': 12, 'perfection': 40.0, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 6, 'stam_iv': 7, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 6, 'stam_iv': 8, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 6, 'stam_iv': 9, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 6, 'stam_iv': 10, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 6, 'stam_iv': 11, 'perfection': 40.0, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 6, 'stam_iv': 12, 'perfection': 42.2, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 7, 'stam_iv': 7, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 7, 'stam_iv': 8, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 7, 'stam_iv': 9, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 7, 'stam_iv': 10, 'perfection': 40.0, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 7, 'stam_iv': 11, 'perfection': 42.2, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 8, 'stam_iv': 7, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 8, 'stam_iv': 8, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 8, 'stam_iv': 9, 'perfection': 40.0, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 9, 'stam_iv': 7, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 9, 'stam_iv': 8, 'perfection': 40.0, 'level': 2.0}, {'atk_iv': 1, 'def_iv': 10, 'stam_iv': 7, 'perfection': 40.0, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 0, 'stam_iv': 7, 'perfection': 20.0, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 0, 'stam_iv': 8, 'perfection': 22.2, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 0, 'stam_iv': 9, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 0, 'stam_iv': 10, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 0, 'stam_iv': 11, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 0, 'stam_iv': 12, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 1, 'stam_iv': 7, 'perfection': 22.2, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 1, 'stam_iv': 8, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 1, 'stam_iv': 9, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 1, 'stam_iv': 10, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 1, 'stam_iv': 11, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 1, 'stam_iv': 12, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 2, 'stam_iv': 7, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 2, 'stam_iv': 8, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 2, 'stam_iv': 9, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 2, 'stam_iv': 10, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 2, 'stam_iv': 11, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 2, 'stam_iv': 12, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 3, 'stam_iv': 7, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 3, 'stam_iv': 8, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 3, 'stam_iv': 9, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 3, 'stam_iv': 10, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 3, 'stam_iv': 11, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 3, 'stam_iv': 12, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 4, 'stam_iv': 7, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 4, 'stam_iv': 8, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 4, 'stam_iv': 9, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 4, 'stam_iv': 10, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 4, 'stam_iv': 11, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 4, 'stam_iv': 12, 'perfection': 40.0, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 5, 'stam_iv': 7, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 5, 'stam_iv': 8, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 5, 'stam_iv': 9, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 5, 'stam_iv': 10, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 6, 'stam_iv': 7, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 6, 'stam_iv': 8, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 6, 'stam_iv': 9, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 7, 'stam_iv': 7, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 2, 'def_iv': 7, 'stam_iv': 8, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 0, 'stam_iv': 7, 'perfection': 22.2, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 0, 'stam_iv': 8, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 0, 'stam_iv': 9, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 0, 'stam_iv': 10, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 0, 'stam_iv': 11, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 0, 'stam_iv': 12, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 1, 'stam_iv': 7, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 1, 'stam_iv': 8, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 1, 'stam_iv': 9, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 1, 'stam_iv': 10, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 1, 'stam_iv': 11, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 1, 'stam_iv': 12, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 2, 'stam_iv': 7, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 2, 'stam_iv': 8, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 2, 'stam_iv': 9, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 2, 'stam_iv': 10, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 2, 'stam_iv': 11, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 2, 'stam_iv': 12, 'perfection': 37.8, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 3, 'stam_iv': 7, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 3, 'stam_iv': 8, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 3, 'stam_iv': 9, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 3, 'stam_iv': 10, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 4, 'stam_iv': 7, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 4, 'stam_iv': 8, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 4, 'stam_iv': 9, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 3, 'def_iv': 5, 'stam_iv': 7, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 4, 'def_iv': 0, 'stam_iv': 7, 'perfection': 24.4, 'level': 2.0}, {'atk_iv': 4, 'def_iv': 0, 'stam_iv': 8, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 4, 'def_iv': 0, 'stam_iv': 9, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 4, 'def_iv': 0, 'stam_iv': 10, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 4, 'def_iv': 0, 'stam_iv': 11, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 4, 'def_iv': 0, 'stam_iv': 12, 'perfection': 35.6, 'level': 2.0}, {'atk_iv': 4, 'def_iv': 1, 'stam_iv': 7, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 4, 'def_iv': 1, 'stam_iv': 8, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 4, 'def_iv': 1, 'stam_iv': 9, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 4, 'def_iv': 1, 'stam_iv': 10, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 4, 'def_iv': 2, 'stam_iv': 7, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 4, 'def_iv': 2, 'stam_iv': 8, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 4, 'def_iv': 2, 'stam_iv': 9, 'perfection': 33.3, 'level': 2.0}, {'atk_iv': 4, 'def_iv': 3, 'stam_iv': 7, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 5, 'def_iv': 0, 'stam_iv': 7, 'perfection': 26.7, 'level': 2.0}, {'atk_iv': 5, 'def_iv': 0, 'stam_iv': 8, 'perfection': 28.9, 'level': 2.0}, {'atk_iv': 5, 'def_iv': 0, 'stam_iv': 9, 'perfection': 31.1, 'level': 2.0}, {'atk_iv': 5, 'def_iv': 1, 'stam_iv': 7, 'perfection': 28.9, 'level': 2.0}]

I am not sure what to make of all that.
Is there a syntax option here or something?

**Comment by tmwilder** [comment]
Hi @ollemonster - thanks for the question. Is your use case to run these one at a time by the command line or to incorporate in something you are working on?

The package ships with a CLI that will pretty print these values for you if you just want that - you could also write something of your own based on the library in cli.py.

**Comment by ollemonster** [comment]
Hi @tmwilder and thanks for the response. I wanted to manually type in all my current pokemons in a delimited text file, then read in each line, running your code on it to get an estimate on how good it is, then write the original line + the result of the IV calc on a line in a new text file, so i the end I have a list that can advice me on which pokemons I should evolve.

So for this usage I need the response to be fairly small, text wise, otherwise it becomes a huge part of each line. I suppose this is because we cannot know exactly the spread over the IV since there are many combinations possible on an average pokemon. I guess if it is 100% or 0 it is easier to calculate.

**Comment by tmwilder** [comment]
Interesting - that seems like a reasonable scenario. If you just want one line per pokemon, would the average be good enough? You could take the mean perfection of every option for each pokemon and output that.

**Comment by ollemonster** [comment]
Good idea. I will try out both using mean perfection and showing minimum and maximum. I am not sure which is the most useful.
